// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Generate(arg1, arg2, arg3, arg4) {
  return window['go']['main']['VocabApp']['Generate'](arg1, arg2, arg3, arg4);
}

export function OpenFile() {
  return window['go']['main']['VocabApp']['OpenFile']();
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['VocabApp']['SaveFile'](arg1, arg2);
}
