// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Generate(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function OpenFile():Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;
